DROP TABLE IF EXISTS task_dependencies CASCADE;
DROP TABLE IF EXISTS tasks CASCADE;
DROP TABLE IF EXISTS event_delivery_status CASCADE;
DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS pipeline_executions CASCADE;
DROP TABLE IF EXISTS pipeline_versions CASCADE;
DROP TABLE IF EXISTS pipelines CASCADE;
